### ISSUE TITLE
Slack Tagging by Role on Study Creation

### ISSUE THREAD

**Issue by CityFriends** [Friends-From-The-City/Qori-Slack-AI-Bot#24]
**Description:**
When a new research study is created with `/new study`, Slack should tag the relevant roles listed in the YAML template (e.g., `@stakeholder`, `@researcher`). This will make it immediately actionable for team members.

**Acceptance Criteria:**
- YAML includes a `notify:` section for roles and actions
- Slack message includes role mentions and specific action items
- Example:
  ```yaml
  notify:
    - role: stakeholder
      action: "Please approve the research study"
      slack_tag: "@jordan"

🔁 **Timing:**
Slack tagging should occur as soon as the study is created and YAML is parsed,
before any approval steps, to ensure all roles are aware and engaged.

🧩 **Role Resolution Strategy:**
- Allow Slack tags to be defined in the YAML (`slack_tag:`)
- If not present, fall back to a global mapping (e.g., `.qori/roles.json`) or look up via Slack user profiles

📣 **Message Format Example:**
```
📣 New Study Created: [Study Title]
👤 Stakeholder: @jordan → Please review and /approve or /reject
🔍 Researcher: @maria → Next step: run /upload-notes
🎨 Designer: @blake → Start design brief with /new-brief
```

⚠️ **Error Handling:**
- If a Slack tag is invalid or user cannot be resolved, post a warning:
  > "No user assigned for role `designer` — please update the YAML or assign manually."
