### ISSUE TITLE
Notes Upload and Tracking via `notes.yaml`

### ISSUE THREAD

**Issue by CityFriends** [Friends-From-The-City/Qori-Slack-AI-Bot#29]
**Description:**
Enable note-takers to upload raw notes to a study and track their upload and summarization status using a centralized `notes.yaml`.

**Acceptance Criteria:**
- Add `/upload-notes` command in Slack
- Upload creates file in `raw_data/notes_TIMESTAMP.md`
- Add or update `notes.yaml` to track uploads
- Example `notes.yaml` file:
  ```yaml
  # notes.yaml
  # Tracks note uploads and summaries for each session in this study

  - session: user_interview_01
    note_taker: "@tariq"
    uploaded: true
    summarized: true
    file_path: raw_data/notes_2025-06-30.md
    summary_path: synthesis/notes_2025-06-30_summary.md
    uploaded_at: 2025-06-30T14:00:00Z
    summarized_at: 2025-06-30T14:03:00Z

  - session: usability_test_round1
    note_taker: "@maria"
    uploaded: false
    summarized: false
    file_path: ""
    summary_path: ""
    uploaded_at: ""
    summarized_at: ""
  ```
- Slack bot automatically reminds assigned note-takers if notes are missing
- Slackbot can summarize uploaded notes using a designated YAML template like `note_upload_handler.yaml`
